name: Threads-graph-ql
services:
  db:
    container_name: graph-db
    image: postgres:17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
